name: '"Tfvars concat" Action for GitHub Actions.'
description: "Concatenate tfvars files in a single file of your choice."
branding:
  color: purple
  icon: chevron-right
inputs:
  tfvars-files-suffix:
    description: Suffix of tfvars files to concatenate.
    required: true
  working-directory:
    description: Working directory where tfvars files are located.
    required: true
  output-file-name:
    description: Name of the output file (eg. prod.tfvars).
    required: true
  blank-line:
    description: Add blank line between files.
    required: false
  print-result:
    description: Print result of the concatenation.
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Concat tfvars files
      shell: bash
      run: $GITHUB_ACTION_PATH/concat.sh
      env:
        TFVARS_FILE_SUFFIX: ${{ inputs.tfvars-files-suffix }}
        WORKING_DIRECTORY: ${{ inputs.working-directory }}
        OUTPUT_FILE_NAME: ${{ inputs.output-file-name }}
        BLANK_LINE: ${{ inputs.blank-line }}
        PRINT_RESULT: ${{ inputs.print-result }}

